"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-15 11:58:06.739405
"""
from collections.abc import Sequence

# sqlmodel is imported because autogenerate renders SQLModel's string type as
# sqlmodel.sql.sqltypes.AutoString, which is unimportable without it.
import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_dir', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'queued', 'running', 'done', 'failed', 'approved', name='imagestatus'), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ocr_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256', name='uq_images_sha256')
    )
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_images_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_status'), ['status'], unique=False)

    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('reading_order', sa.Integer(), nullable=False),
    sa.Column('rec_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('corrected_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('polygon', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('unreviewed', 'approved', 'edited', name='linestatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lines_image_id'), ['image_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lines_image_id'))

    op.drop_table('lines')
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_status'))
        batch_op.drop_index(batch_op.f('ix_images_sha256'))
        batch_op.drop_index(batch_op.f('ix_images_batch_id'))

    op.drop_table('images')
    op.drop_table('batches')
    # ### end Alembic commands ###
