"""perf indexes

Revision ID: 0002_perf_indexes
Revises: 0001_baseline
Create Date: 2026-09-15 12:02:09.629456
"""
from collections.abc import Sequence

# sqlmodel is imported because autogenerate renders SQLModel's string type as
# sqlmodel.sql.sqltypes.AutoString, which is unimportable without it.
import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '0002_perf_indexes'
down_revision: str | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index('ix_batches_created_at_id', ['created_at', 'id'], unique=False)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_images_batch_id'))
        batch_op.drop_index(batch_op.f('ix_images_sha256'))
        batch_op.drop_index(batch_op.f('ix_images_status'))
        batch_op.create_index('ix_images_batch_id_filename_id', ['batch_id', 'filename', 'id'], unique=False)
        batch_op.create_index('ix_images_batch_id_status', ['batch_id', 'status'], unique=False)

    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lines_image_id'))
        batch_op.create_index('ix_lines_image_id_reading_order', ['image_id', 'reading_order'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lines', schema=None) as batch_op:
        batch_op.drop_index('ix_lines_image_id_reading_order')
        batch_op.create_index(batch_op.f('ix_lines_image_id'), ['image_id'], unique=False)

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_index('ix_images_batch_id_status')
        batch_op.drop_index('ix_images_batch_id_filename_id')
        batch_op.create_index(batch_op.f('ix_images_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_images_batch_id'), ['batch_id'], unique=False)

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index('ix_batches_created_at_id')

    # ### end Alembic commands ###
